name: Build Triton
description: |
  Build Triton from a specified commit. This composite action will:
  - check if a GitHub artifact exists for this LLVM commit, OS, and architecture: `llvm-<short-hash>-<os>-<arch>`
  - if the artifact does not exist, check out LLVM and build it _as shared libraries_ (required for triton-ext); then,
    upload it as an artifact
  - if the artifact does exist, download and extract it
  - return the path the LLVM installation directory.

inputs:
  triton_hash:
    description: Triton commit hash to build.
    required: true
  llvm_install_dir:
    description: The LLVM installation directory.
    required: true
outputs:
  triton_install_dir:
    description: The Triton installation directory.
    value: ${{ steps.setup.outputs.triton_install_dir }}
  triton_build_dir:
    description: The Triton build directory.
    value: ${{ steps.build.outputs.triton_build_dir }}

runs:
  using: composite
  steps:
    - name: Determine Triton installation directory
      id: setup
      shell: bash
      run: |
        TRITON_INSTALL_DIR="${{ github.workspace }}/triton"
        echo "Triton installation directory: ${TRITON_INSTALL_DIR}"
        echo "triton_install_dir=${TRITON_INSTALL_DIR}" >> ${GITHUB_ENV}
        echo "triton_install_dir=${TRITON_INSTALL_DIR}" >> ${GITHUB_OUTPUT}

    - name: Checkout triton
      uses: actions/checkout@v4
      with:
        repository: triton-lang/triton
        ref: ${{ inputs.triton_hash }}
        path: ${{ steps.setup.outputs.triton_install_dir }}

    - name: Setup sccache
      uses: mozilla-actions/sccache-action@v0.0.6

    - name: Build Triton
      id: build
      working-directory: ${{ steps.setup.outputs.triton_install_dir }}
      shell: bash
      run: >
        TRITON_BUILD_WITH_CLANG_LLD=1
        CMAKE_C_COMPILER_LAUNCHER=sccache
        CMAKE_CXX_COMPILER_LAUNCHER=sccache
        LLVM_INCLUDE_DIRS=${{ inputs.llvm_install_dir }}/include
        LLVM_LIBRARY_DIR=${{ inputs.llvm_install_dir }}/lib
        LLVM_SYSPATH=${{ inputs.llvm_install_dir }}
        make dev-install

        TRITON_BUILD_DIR="$(pwd)/build/cmake.*"
        echo "triton_build_dir=${TRITON_BUILD_DIR}" >> $GITHUB_ENV
        echo "triton_build_dir=${TRITON_BUILD_DIR}" >> $GITHUB_OUTPUT

    - name: Dump Sccache Statistics
      shell: bash
      run: sccache --show-stats
