name: Build LLVM

on:
  push:
    paths:
      - '.github/workflows/**'
  schedule:
    # Run daily to check for upstream changes
    - cron: '0 0 * * *'
  # We can also trigger this workflow (a) manually and (b) from another workflow. If we pass the LLVM commit has as
  # input, we build from that; otherwise, we fetch the latest LLVM commit hash from Triton's main branch.
  workflow_dispatch:
    inputs:
      llvm_hash:
        required: false
        type: string
  workflow_call:
    inputs:
      llvm_hash:
        required: false
        type: string

permissions:
  contents: read

env:
  SCCACHE_DIR: ${{ github.workspace }}/sccache

jobs:
  build-llvm:
    name: Build on ${{ matrix.config.runner }}
    runs-on: ${{ matrix.config.runs_on }}
    timeout-minutes: 300

    strategy:
      fail-fast: true
      matrix:
        config:
        - {runner: 'Ubuntu 22.04', runs_on: 'ubuntu-22.04', target-os: 'ubuntu', arch: 'x64'}
        # - {runner: 'Ubuntu 22.04 ARM64', runs_on: 'ubuntu-22.04', target-os: 'ubuntu', arch: 'arm64'}
        # - {runner: 'AlmaLinux 8', runs_on: ['self-hosted', 'CPU'], target-os: 'almalinux', arch: 'x64'}
        # - {runner: 'AlmaLinux 8 ARM64', runs_on: 'ubuntu-22.04-arm', target-os: 'almalinux', arch: 'arm64'}
        # - {runner: 'MacOS X64', runs_on: 'macos-15', target-os: 'macos', arch: 'x64'}
        # - {runner: 'MacOS ARM64', runs_on: 'macos-15', target-os: 'macos', arch: 'arm64'}
        # - {runner: 'Windows Latest', runs_on: 'windows-latest', target-os: 'windows', arch: 'x64'}

    steps:
      - name: Checkout triton-ext
        uses: actions/checkout@v4

      - name: Build LLVM (composite action)
        uses: ./.github/actions/build-llvm
        with:
          llvm_hash: ${{ inputs.llvm_hash }}
