name: CI
description: |
  Continuous integration workflow for triton-ext.
  - Build triton-ext dependencies: LLVM and Triton
  - Create a parallel directory structure in the workspace: `triton-ext`, `triton`, and `llvm-<hash>-<os>-<arch>`.

on:
  push:
    paths:
      - '.github/workflows/**'
      - '.github/actions/**'
  schedule:
    # Run daily to check for upstream changes
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: read

env:
  SCCACHE_DIR: ${{ github.workspace }}/sccache

jobs:
  build:
    name: Build on ${{ matrix.config.runner }}
    runs-on: ${{ matrix.config.runs_on }}
    timeout-minutes: 300

    strategy:
      fail-fast: true
      matrix:
        config:
        - {runner: 'Ubuntu 22.04', runs_on: 'ubuntu-22.04', target-os: 'ubuntu', arch: 'x64'}
        # - {runner: 'Ubuntu 22.04 ARM64', runs_on: 'ubuntu-22.04', target-os: 'ubuntu', arch: 'arm64'}
        # - {runner: 'AlmaLinux 8', runs_on: ['self-hosted', 'CPU'], target-os: 'almalinux', arch: 'x64'}
        # - {runner: 'AlmaLinux 8 ARM64', runs_on: 'ubuntu-22.04-arm', target-os: 'almalinux', arch: 'arm64'}
        # - {runner: 'MacOS X64', runs_on: 'macos-15', target-os: 'macos', arch: 'x64'}
        # - {runner: 'MacOS ARM64', runs_on: 'macos-15', target-os: 'macos', arch: 'arm64'}
        # - {runner: 'Windows Latest', runs_on: 'windows-latest', target-os: 'windows', arch: 'x64'}

    steps:
      - name: Checkout triton-ext
        uses: actions/checkout@v4
        with:
          path: triton-ext

      - name: Collect commit hashes
        id: hashes
        shell: bash
        run: |
          TRITON_HASH=$(triton-ext/ci/fetch-triton-hash.py)
          echo "triton_hash=$TRITON_HASH" >> $GITHUB_OUTPUT
          echo "Triton hash: $TRITON_HASH"

          LLVM_HASH=$(triton-ext/ci/fetch-llvm-hash-from-triton.py $TRITON_HASH)
          echo "llvm_hash=$LLVM_HASH" >> $GITHUB_OUTPUT
          echo "LLVM hash: $LLVM_HASH"

      - name: Build LLVM
        id: build-llvm
        uses: triton-ext/.github/actions/build-llvm
        with:
          llvm_hash: ${{ steps.hashes.outputs.llvm_hash }}

      - name: Build Triton
        id: build-triton
        uses: triton-ext/.github/actions/build-triton
        with:
          triton_hash: ${{ steps.hashes.outputs.triton_hash }}
          llvm_install_dir: ${{ steps.build-llvm.outputs.llvm_install_dir }}

      - name: List files
        shell: bash
        run: |
          echo "LLVM installation directory contents:"
          du -h .

